# --------------------------------------------------------------------------
# Riley: A High Performance Rasteriser for DIC UQ
#
# Copyright (c) 2025-2026 scepticalrabbit (Lloyd Fletcher)
# Licensed under the MIT License (see LICENSE file for details)
#
# Authors: scepticalrabbit (Lloyd Fletcher)
# --------------------------------------------------------------------------
import os
import platform
from pathlib import Path

from riley import data
from riley import python

# Add DLL directory to the search path on Windows to avoid "DLL load failed"
if platform.system().lower() == "windows":
    _current_dir = Path(__file__).resolve().parent
    # Search zig/ and cython/ subdirectories where DLLs are located
    for _sub_dir in ("zig", "cython"):
        _dll_dir = _current_dir / _sub_dir
        if _dll_dir.is_dir():
            try:
                os.add_dll_directory(str(_dll_dir))
            except AttributeError:
                # Fallback for older Python versions
                pass

from riley.cython.riley import (
    BufferMode,
    Camera,
    CameraCoordSys,
    CameraInput,
    EFrameFit,
    FrameFitMode,
    FuncCoordMode,
    FuncShaderBuiltin,
    FuncShaderParams,
    FunctionShader,
    GeometrySchedulingMode,
    HullMode,
    ImageFormat,
    ImageSaveMode,
    Mesh,
    MeshType,
    NewtonSeedMode,
    NewtonSeedReuse,
    NodalShader,
    NormalType,
    PsfType,
    RasterConfig,
    RenderMode,
    ReportMode,
    RileyShader,
    SaveStrategy,
    ScaleOver,
    ScaleStrategy,
    Shader,
    SubPixelCenterMap,
    TextureSample,
    TextureSampleMode,
    TextureShader,
    calc_pixel_resolution,
    coverage_to_fov_scale,
    fov_scale_to_coverage,
    load_camera,
    load_stereo_pair,
    pos_fill_frame_from_rot,
    pos_fill_frame_from_rot_over_meshes,
    pos_frame_coords,
    pos_frame_mesh,
    pos_frame_meshes,
    pos_orbit_cam,
    pos_stereo_pair,
    raster,
    roi_cent_from_coords,
    roi_cent_over_meshes,
    save_camera,
    save_stereo_pair,
)
from riley.python import (
    exodusio,
    frameops,
    meshconst,
    meshconv,
    meshio,
    rileyconfig,
    sceneops,
    textureio,
    uvtools,
)
from riley.python.exodusio import (
    ExodusBlock,
    ExodusError,
    ExodusSim,
    load_exodus,
)
from riley.python.frameops import (
    frames_evenly_spaced_idxs,
    frames_first_last_idxs,
    frames_select,
)
from riley.python.meshconst import (
    EElemType,
    RileyElemTopology,
)
from riley.python.meshconv import (
    ConnectConvention,
    EConnectAxis,
    EdgeNode,
    ENodeOrder,
    FaceNode,
    MeshError,
    MeshGeometry,
    MeshVerifyIssue,
    UserTopology,
    convert_mesh,
    extract_surface,
    reduce_mesh_order,
    triangulate_mesh,
    verify_mesh,
)
from riley.python.meshio import (
    MeshConversion,
    convert_mesh_for_render,
    create_mesh,
    create_mesh_from_conversion,
    create_mesh_from_prepared,
    load_csv,
    remap_nodal_data,
)
from riley.python.rileyconfig import create_raster_config
from riley.python.sceneops import (
    ESceneOverlapDirect,
    SceneBounds3D,
    SceneBoundsOverlapSpec,
    SceneGridSpec,
    SceneMeshGroup,
    scene_arrange_mesh_groups_grid,
    scene_calc_bounds_for_coords,
    scene_calc_bounds_for_coords_list,
    scene_calc_bounds_for_mesh_group,
    scene_center_mesh_group_at,
    scene_create_mesh_group_single,
    scene_create_mesh_group_span,
    scene_overlap_mesh_group_bounds,
    scene_translate_mesh_group,
)
from riley.python.textureio import (
    ETextureCoercion,
    load_texture_mono_u8,
    load_texture_mono_u16,
    load_texture_rgb_u8,
)
from riley.python.uvtools import (
    EUVPlanarProjMode,
    EUVProjPlane,
    UVPixelBBox,
    UVProjAxes,
    UVProjBounds2D,
    UVProjPlane,
    project_uvs_planar_bbox,
    project_uvs_planar_centered,
)

__all__ = [
    "BufferMode",
    "Camera",
    "CameraCoordSys",
    "CameraInput",
    "ConnectConvention",
    "EConnectAxis",
    "EElemType",
    "EFrameFit",
    "ENodeOrder",
    "ESceneOverlapDirect",
    "ETextureCoercion",
    "EUVPlanarProjMode",
    "EUVProjPlane",
    "EdgeNode",
    "ExodusBlock",
    "ExodusError",
    "ExodusSim",
    "FaceNode",
    "FrameFitMode",
    "FuncCoordMode",
    "FuncShaderBuiltin",
    "FuncShaderParams",
    "FunctionShader",
    "GeometrySchedulingMode",
    "HullMode",
    "ImageFormat",
    "ImageSaveMode",
    "Mesh",
    "MeshConversion",
    "MeshError",
    "MeshGeometry",
    "MeshType",
    "MeshVerifyIssue",
    "NewtonSeedMode",
    "NewtonSeedReuse",
    "NodalShader",
    "NormalType",
    "PsfType",
    "RasterConfig",
    "RenderMode",
    "ReportMode",
    "RileyElemTopology",
    "RileyShader",
    "SaveStrategy",
    "ScaleOver",
    "ScaleStrategy",
    "SceneBounds3D",
    "SceneBoundsOverlapSpec",
    "SceneGridSpec",
    "SceneMeshGroup",
    "Shader",
    "SubPixelCenterMap",
    "TextureSample",
    "TextureSampleMode",
    "TextureShader",
    "UVPixelBBox",
    "UVProjAxes",
    "UVProjBounds2D",
    "UVProjPlane",
    "UserTopology",
    "calc_pixel_resolution",
    "convert_mesh",
    "convert_mesh_for_render",
    "coverage_to_fov_scale",
    "create_mesh",
    "create_mesh_from_conversion",
    "create_mesh_from_prepared",
    "create_raster_config",
    "data",
    "exodusio",
    "extract_surface",
    "fov_scale_to_coverage",
    "frameops",
    "frames_evenly_spaced_idxs",
    "frames_first_last_idxs",
    "frames_select",
    "load_camera",
    "load_csv",
    "load_exodus",
    "load_stereo_pair",
    "load_texture_mono_u8",
    "load_texture_mono_u16",
    "load_texture_rgb_u8",
    "meshconst",
    "meshconv",
    "meshio",
    "pos_fill_frame_from_rot",
    "pos_fill_frame_from_rot_over_meshes",
    "pos_frame_coords",
    "pos_frame_mesh",
    "pos_frame_meshes",
    "pos_orbit_cam",
    "pos_stereo_pair",
    "project_uvs_planar_bbox",
    "project_uvs_planar_centered",
    "python",
    "raster",
    "reduce_mesh_order",
    "remap_nodal_data",
    "rileyconfig",
    "roi_cent_from_coords",
    "roi_cent_over_meshes",
    "save_camera",
    "save_stereo_pair",
    "scene_arrange_mesh_groups_grid",
    "scene_calc_bounds_for_coords",
    "scene_calc_bounds_for_coords_list",
    "scene_calc_bounds_for_mesh_group",
    "scene_center_mesh_group_at",
    "scene_create_mesh_group_single",
    "scene_create_mesh_group_span",
    "scene_overlap_mesh_group_bounds",
    "scene_translate_mesh_group",
    "sceneops",
    "textureio",
    "triangulate_mesh",
    "uvtools",
    "verify_mesh",
]
